[package]
name = "wordcell-solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bip0039 = "0.10.1"
solana-sdk = "1.14.5"
regex = "1"
